[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"
  MY_ENV_KEY = "value"
  ANOTHER_KEY = "value"
[build]
  command = "npm run build"
  publish = "out"

[build.environment]
  NEXT_PUBLIC_ARBITRUM_BUILDER_ADDRESS = "0xC0eD68f163d44B6e9985F0041fDf6f67c6BCFF3f"
  NEXT_PUBLIC_ARBITRUM_TREASURY_ADDRESS = "0xCBE3d2c3AdE62cf7aa396e8cA93D2A8bff96E257"
  NEXT_PUBLIC_ARBITRUM_FEE_CONFIG_ADDRESS = "0xc03d87085E254695754a74D2CF76579e167Eb895"

  NEXT_PUBLIC_BASE_BUILDER_ADDRESS = "0x42BB446eAE6dca7723a9eBdb81EA88aFe77eF4B9"
  NEXT_PUBLIC_BASE_TREASURY_ADDRESS = "0x9eba628581896ce086cb8f1A513ea6097A8FC561"
  NEXT_PUBLIC_BASE_FEE_CONFIG_ADDRESS = "0x845FBB4B3e2207BF03087b8B94D2430AB11088eE"

  NEXT_PUBLIC_MOR_TOKEN_ARBITRUM = "0x092baadb7def4c3981454dd9c0a0d7ff07bcfc86"
  NEXT_PUBLIC_L2_TOKEN_RECEIVER_V2 = "0x47176b2af9885dc6c4575d4efd63895f7aaa4790"
  NEXT_PUBLIC_L2_MESSAGE_RECEIVER = "0xd4a8ECcBe696295e68572A98b1aA70Aa9277d427"
  NEXT_PUBLIC_MORPHEUS_MULTISIG_ARBITRUM = "0x1FE04BC15Cf2c5A2d41a0b3a96725596676eBa1E"
  NEXT_PUBLIC_MOR_BURN_ADDRESS = "0x000000000000000000000000000000000000dead"
  NEXT_PUBLIC_MOR_LOCK_ADDRESS = "0xb1972e86b3380fd69dcb395f98d39fbf1a5f305a"

  NEXT_PUBLIC_MOR_TOKEN_BASE = "0x7431ada8a591c955a994a21710752ef9b882b8e3"
  NEXT_PUBLIC_MORPHEUS_MULTISIG_BASE = "0x1FE04BC15Cf2c5A2d41a0b3a96725596676eBa1E"

  NEXT_PUBLIC_MOR_TOKEN_ETHEREUM = "0xcBB8f1BDA10b9696c57E13BC128Fe674769DCEc0"
  NEXT_PUBLIC_DISTRIBUTION_ETHEREUM = "0x47176B2Af9885dC6C4575d4eFd63895f7Aaa4790"
  NEXT_PUBLIC_L1_SENDER = "0x2Efd4430489e1a05A89c2f51811aC661B7E5FF84"
  NEXT_PUBLIC_MORPHEUS_MULTISIG_ETHEREUM = "0x1FE04BC15Cf2c5A2d41a0b3a96725596676eBa1E"

  NEXT_PUBLIC_ARBITRUM_RPC_URL = "https://arbitrum-mainnet.infura.io/v3/ecbb7fb016fc4f859469f48787bc67c0"
  NEXT_PUBLIC_BASE_RPC_URL = "https://base-mainnet.infura.io/v3/ecbb7fb016fc4f859469f48787bc67c0"

  POLYGON_MAINNET_RPC_URL = "https://polygon-mainnet.infura.io/v3/ecbb7fb016fc4f859469f48787bc67c0"
  POLYGON_AMOY_RPC_URL = "https://polygon-amoy.infura.io/v3/ecbb7fb016fc4f859469f48787bc67c0"
  OPTIMISM_MAINNET_RPC_URL = "https://optimism-mainnet.infura.io/v3/ecbb7fb016fc4f859469f48787bc67c0"
  OPTIMISM_SEPOLIA_RPC_URL = "https://optimism-sepolia.infura.io/v3/ecbb7fb016fc4f859469f48787bc67c0"
  ARBITRUM_SEPOLIA_RPC_URL = "https://arbitrum-sepolia.infura.io/v3/ecbb7fb016fc4f859469f48787bc67c0"
  AVALANCHE_MAINNET_RPC_URL = "https://avalanche-mainnet.infura.io/v3/ecbb7fb016fc4f859469f48787bc67c0"
  AVALANCHE_FUJI_RPC_URL = "https://avalanche-fuji.infura.io/v3/ecbb7fb016fc4f859469f48787bc67c0"

  POLYGON_RPC_URL = "https://polygon-mumbai.infura.io/v3/ecbb7fb016fc4f859469f48787bc67c0"
  POLYGON_CHAIN_ID = "80001"
  POLYGON_NETWORK_NAME = "Mumbai"

  ETH_MAINNET_RPC_URL = "https://mainnet.infura.io/v3/ecbb7fb016fc4f859469f48787bc67c0"
  ETH_SEPOLIA_RPC_URL = "https://sepolia.infura.io/v3/ecbb7fb016fc4f859469f48787bc67c0"
  ETH_HOLESKY_RPC_URL = "https://holesky.infura.io/v3/ecbb7fb016fc4f859469f48787bc67c0"

  NEXT_PUBLIC_ENVIRONMENT = "development"
  ENABLE_TESTNET = "true"

  INFURA_API_KEY = "ecbb7fb016fc4f859469f48787bc67c0"
  INFURA_API_SECRET = "gWfHGDonXLZ4GOuIfXch2fqzjH3x05uj5nSk1Zwk/dsotyqUpxsL5A"
  ALCHEMY_API_KEY = "QOeBQdwKcWQuaIVh-vZzDVjJxTNVKHNz"
  POLYGON_API_KEY = "QOeBQdwKcWQuaIVh-vZzDVjJxTNVKHNz"
  ETHERSCAN_API_KEY = "1QAR2FAFP1Y2AY8HJXN2VXJRK1X9GE29M2"

  IPFS_PROJECT_ID = ""
  IPFS_PROJECT_SECRET = ""
  IPFS_GATEWAY = "https://ipfs.io/ipfs/"

  FIREBASE_API_KEY = ""
  FIREBASE_AUTH_DOMAIN = ""
  FIREBASE_PROJECT_ID = "all-the-ai"
  FIREBASE_STORAGE_BUCKET = ""
  FIREBASE_MESSAGING_SENDER_ID = ""
  FIREBASE_APP_ID = ""

  PRIVATE_KEY_TEST = ""
  TEST_ACCOUNT_ADDRESS = ""

  RATE_LIMIT_REQUESTS = "100"
  RATE_LIMIT_WINDOW_MS = "900000"

  ENABLE_FEATURE_MARKET = "true"
  ENABLE_AGENT_MARKETPLACE = "true"
  ENABLE_DEVELOPER_REGISTRY = "true"

  MINIMUM_STAKE_AMOUNT = "10"
  PLATFORM_FEE_BPS = "250"

  GAS_API_URL = "https://gas.api.infura.io/v3/ecbb7fb016fc4f859469f48787bc67c0"

  NEXT_PUBLIC_FEATURE_MARKET_ADDRESS = ""
  NEXT_PUBLIC_REPUTATION_SYSTEM_ADDRESS = ""
  NEXT_PUBLIC_STAKING_ADDRESS = ""

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
